steps:
  # 1. Deploy da Cloud Function FECHADA para o mundo
  # Removemos --allow-unauthenticated e adicionamos --ingress-settings=internal-and-cloud-load-balancing
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        SECRET_VAL=$(gcloud secrets versions access latest --secret="STARWARS_API_KEY")
        
        gcloud functions deploy starwars-backend \
          --gen2 \
          --runtime=python311 \
          --region=us-central1 \
          --source=. \
          --entry-point=starwars_api \
          --trigger-http \
          --no-allow-unauthenticated \
          --ingress-settings=internal-and-cloud-load-balancing \
          --set-env-vars=API_KEY=$$SECRET_VAL

  # 2. Criar nova configuração do API Gateway
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - api-gateway
      - api-configs
      - create
      - sw-config-${SHORT_SHA}
      - --api=sw-api
      - --openapi-spec=gcp-api-gateway.yaml
      - --backend-auth-service-account=587782644081-compute@developer.gserviceaccount.com \
      - --project=${PROJECT_ID}

  # 3. Atualizar o Gateway
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - api-gateway
      - gateways
      - update
      - sw-gateway
      - --api=sw-api
      - --api-config=sw-config-${SHORT_SHA}
      - --location=us-central1
      - --project=${PROJECT_ID}

options:
  logging: CLOUD_LOGGING_ONLY
