swagger: "2.0"
info:
  title: Star Wars API Gateway
  description: Gateway que repassa as requisições para o FastAPI.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  api_key:
    type: apiKey
    name: access_token
    in: header

paths:
  /{path}:
    get:
      summary: Proxy Nível 1
      operationId: proxyLevel1
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app/{path}
      parameters:
        - name: path
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK

  /{path}/{subpath}:
    get:
      summary: Proxy Nível 2
      operationId: proxyLevel2
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app/{path}/{subpath}
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: subpath
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK
