swagger: "2.0"
info:
  title: Star Wars API Gateway
  description: Gateway simplificado para garantir entrega do desafio.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-token
    in: header

paths:
  /people:
    get:
      summary: People List
      operationId: getPeopleFinal
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app
      responses:
        "200":
          description: OK
  /planets:
    get:
      summary: Planets List
      operationId: getPlanetsFinal
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app
      responses:
        "200":
          description: OK
  /films:
    get:
      summary: Films List
      operationId: getFilmsFinal
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app
      responses:
        "200":
          description: OK
  /docs:
    get:
      summary: Swagger UI
      operationId: getDocsFinal
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app
      responses:
        "200":
          description: OK
