swagger: "2.0"
info:
  title: Star Wars API Gateway
  description: Gateway simplificado para garantir entrega do desafio.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-token
    in: header

paths:
  /people:
    get:
      summary: People List
      operationId: getPeopleList
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /people/{person_id}:
    get:
      summary: Person Detail
      operationId: getPersonDetail
      parameters:
        - name: person_id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /planets:
    get:
      summary: Planets List
      operationId: getPlanetsList
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /planets/{planet_id}:
    get:
      summary: Planet Detail
      operationId: getPlanetDetail
      parameters:
        - name: planet_id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /films:
    get:
      summary: Films List
      operationId: getFilmsList
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /films/{film_id}:
    get:
      summary: Film Detail
      operationId: getFilmDetail
      parameters:
        - name: film_id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /films/{film_id}/people:
    get:
      summary: Film Characters
      operationId: getFilmPeople
      parameters:
        - name: film_id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /species:
    get:
      summary: Species List
      operationId: getSpeciesList
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /species/{species_id}:
    get:
      summary: Species Detail
      operationId: getSpeciesDetail
      parameters:
        - name: species_id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /starships:
    get:
      summary: Starships List
      operationId: getStarshipsList
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /starships/{starship_id}:
    get:
      summary: Starship Detail
      operationId: getStarshipDetail
      parameters:
        - name: starship_id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /vehicles:
    get:
      summary: Vehicles List
      operationId: getVehiclesList
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /vehicles/{vehicle_id}:
    get:
      summary: Vehicle Detail
      operationId: getVehicleDetail
      parameters:
        - name: vehicle_id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /docs:
    get:
      summary: Swagger UI
      operationId: getSwaggerDocs
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /redoc:
    get:
      summary: ReDoc
      operationId: getRedoc
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /openapi.json:
    get:
      summary: OpenAPI Specification
      operationId: getOpenAPISpec
      x-google-backend:
        address: BACKEND_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
