swagger: "2.0"
info:
  title: Star Wars API Gateway
  description: Gateway Universal (Proxy) para FastAPI
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  api_key:
    type: apiKey
    name: access_token
    in: header

paths:
  # O segredo está aqui: capturamos a raiz e ordenamos que o Google
  # APENAS ADICIONE o resto do caminho à URL do backend.
  /:
    get:
      summary: Proxy Universal
      operationId: universalProxyRoot
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK
  /{path}:
    get:
      summary: Proxy Universal Nível 1
      operationId: universalProxyLevel1
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: path
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK
  /{path}/{subpath}:
    get:
      summary: Proxy Universal Nível 2
      operationId: universalProxyLevel2
      x-google-backend:
        address: https://starwars-backend-r7r24kg6uq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: subpath
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK
